sa-token:
  active-timeout: -1
  is-concurrent: true
  is-log: true
  is-share: true
  timeout: 2592000
  token-name: soybean
  token-prefix: Bearer
  token-style: random-64


server:
  port: 8090

mybatis-flex:
  mapper-locations: classpath*:/mapper/**/*.xml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/pwa?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver

# ??swagger???????????????SpringBoot
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher